### ISSUE TITLE
Collection view isn't scrolling to the last item if the item count is not divisible by 3

### ISSUE THREAD

**Issue by lennathe** [vinnyoodles/TRMosaicLayout#8]
Hi,

Your library is great! Just found out that collection view isn't scrolling to the last item if the item count is not divisible by 3..it happens in your example code too..
Could you please fix it?

Thanks

**Comment by lennathe** [comment]
Sorry it turn out that this has been fixed in the previous issue, I didn't see it before :)

**Comment by andrealufino** [comment]
This still happening to me. If my count is not divisible by 3, the last elements cannot be scrolled. Is there a way to avoid it?

**Comment by Alex293** [comment]
Look a the previous issue. The fix is not merged in the repo you need to manually add this to your project. Issue #4
